const fs = require('fs');
const code = `"use client";
import{useEffect,useState,useCallback}from"react";import{useSession}from"next-auth/react";import{useRouter}from"next/navigation";import{Shield,RefreshCw,Check,X,ArrowDownLeft,ArrowUpRight}from"lucide-react";

export default function AdminPage(){
const{data:session,status}=useSession();const router=useRouter();
const[tab,setTab]=useState("pools");const[pools,setPools]=useState([]);const[users,setUsers]=useState([]);const[deposits,setDeposits]=useState([]);const[withdrawals,setWithdrawals]=useState([]);const[stats,setStats]=useState({u:0,i:0,v:0,p:0});

useEffect(()=>{if(status==="unauthenticated")router.push("/auth/signin");else if(status==="authenticated"&&session?.user?.role!=="admin")router.push("/dashboard")},[status,session,router]);

const load=useCallback(async()=>{try{const[r1,r2,r3,r4]=await Promise.all([fetch("/api/admin/pools"),fetch("/api/admin/users"),fetch("/api/admin/deposits"),fetch("/api/admin/withdrawals")]);const[d1,d2,d3,d4]=await Promise.all([r1.json(),r2.json(),r3.json(),r4.json()]);setPools(d1.pools||[]);setUsers(d2.users||[]);setDeposits(d3.deposits||[]);setWithdrawals(d4.withdrawals||[]);setStats({u:d2.count||0,i:d2.totalInvestments||0,v:d2.totalVolume||0,p:d1.count||0})}catch(e){console.error(e)}},[]);

useEffect(()=>{if(session?.user?.role==="admin")load()},[session,load]);

const block=async(id,s)=>{const n=s==="blocked"?"active":"blocked";await fetch(\`/api/admin/users/\${id}/block\`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:n})});setUsers(p=>p.map(u=>u.id===id?{...u,status:n}:u))};
const dep=async(id,a)=>{await fetch("/api/admin/deposits",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({transactionId:id,action:a})});setDeposits(p=>p.map(d=>d.id===id?{...d,status:a==="approve"?"confirmed":"rejected"}:d))};
const wit=async(id,a)=>{await fetch("/api/admin/withdrawals",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({withdrawalId:id,action:a})});setWithdrawals(p=>p.map(w=>w.id===id?{...w,status:a==="approve"?"approved":"rejected"}:w))};

const B=({s}:{s:string})=>{const c:Record<string,string>={confirmed:"bg-emerald-500/20 text-emerald-400",approved:"bg-emerald-500/20 text-emerald-400",active:"bg-emerald-500/20 text-emerald-400",pending:"bg-amber-500/20 text-amber-400",rejected:"bg-red-500/20 text-red-400",blocked:"bg-red-500/20 text-red-400",inactive:"bg-gray-500/20 text-gray-400"};return<span className={\`px-2 py-1 rounded-full text-xs font-medium \${c[s]||"bg-gray-500/20 text-gray-400"}\`}>{s}</span>};

const tabs=[{k:"pools",l:"Pools"},{k:"deposits",l:"Deposits",c:deposits.filter((d:any)=>d.status==="pending").length},{k:"withdrawals",l:"Withdrawals",c:withdrawals.filter((w:any)=>w.status==="pending").length},{k:"users",l:"Users"}];

if(status==="loading")return<div className="min-h-screen flex items-center justify-center bg-gray-950 text-gray-500">Loading...</div>;

return(
<div className="p-4 lg:p-8 bg-gray-950 min-h-screen">
<div className="mb-8 flex items-center justify-between flex-wrap gap-4">
<div className="flex items-center gap-3"><div className="w-12 h-12 rounded-xl bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center"><Shield className="w-6 h-6 text-white"/></div><div><h1 className="text-2xl lg:text-3xl font-bold text-white">Admin Panel</h1><p className="text-gray-400 text-sm">Manage pools, users, deposits, withdrawals</p></div>
<button onClick={load} className="px-4 py-2 bg-gray-800 hover:bg-gray-700 rounded-lg text-gray-300 transition-colors flex items-center gap-2 text-sm"><RefreshCw className="w-4 h-4"/>Refresh</button>
</div>

<div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
{[{l:"Total Users",v:stats.u},{l:"Active Pools",v:stats.p},{l:"Investments",v:stats.i},{l:"Volume",v:\`$\${stats.v.toLocaleString()}\`}].map(s=>(<div key={s.l} className="bg-gray-900/60 border border-gray-800 rounded-xl p-4 lg:p-6"><p className="text-2xl font-bold text-white">{s.v}</p><p className="text-gray-400 text-sm">{s.l}</p></div>))}
</div>

<div className="flex flex-wrap gap-2 mb-6 border-b border-gray-800 pb-4">
{tabs.map(t=>(<button key={t.k} onClick={()=>setTab(t.k)} className={\`px-4 py-2 rounded-lg font-medium transition-all capitalize text-sm flex items-center gap-2 \${tab===t.k?"bg-cyan-500/20 text-cyan-400 border border-cyan-500/30":"text-gray-400 hover:text-white hover:bg-gray-800/50"}\`}>{t.l}{(t.c||0)>0&&<span className="px-1.5 py-0.5 bg-red-500/20 text-red-400 text-xs rounded-full">{t.c}</span>}</button>))}
</div>

{tab==="pools"&&(<div className="bg-gray-900/60 border border-gray-800 rounded-xl overflow-hidden"><div className="p-4 lg:p-6 border-b border-gray-800"><h2 className="text-xl font-bold text-white">Pools ({pools.length})</h2></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-800">{["Name","Min/Max","Daily","Duration","Invested","Status"].map(h=>(<th key={h} className="px-4 lg:px-6 py-3 text-left text-xs font-medium text-gray-400 uppercase">{h}</th>))}</tr></thead><tbody>{pools.map((p:any)=>(<tr key={p.id} className="border-b border-gray-800/50 hover:bg-gray-800/30"><td className="px-4 lg:px-6 py-3"><p className="font-semibold text-white">{p.name}</p><p className="text-xs text-gray-500">{p.description}</p></td><td className="px-4 lg:px-6 py-3 text-gray-300">${p.minimumInvestment}/{p.maximumInvestment||"∞"}</td><td className="px-4 lg:px-6 py-3 text-emerald-400 font-bold">{p.dailyReturn}%</td><td className="px-4 lg:px-6 py-3 text-gray-300">{p.durationDays}d</td><td className="px-4 lg:px-6 py-3 text-gray-300">${Number(p.totalInvested).toLocaleString()}</td><td className="px-4 lg:px-6 py-3"><B s={p.isActive?"active":"inactive"}/></td></tr>))}</tbody></table></div>)}

{tab==="deposits"&&(<div className="bg-gray-900/60 border border-gray-800 rounded-xl overflow-hidden"><div className="p-4 lg:p-6 border-b border-gray-800"><h2 className="text-xl font-bold text-white flex items-center gap-2"><ArrowDownLeft className="w-5 h-5 text-emerald-400"/>Deposits</h2></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-800">{["User","Amount","Network","TxID","Date","Status","Actions"].map(h=>(<th key={h} className="px-4 lg:px-6 py-3 text-left text-xs font-medium text-gray-400 uppercase">{h}</th>))}</tr></thead><tbody>{deposits.map((d:any)=>(<tr key={d.id} className="border-b border-gray-800/50 hover:bg-gray-800/30"><td className="px-4 lg:px-6 py-3"><p className="text-white font-medium">{d.user?.name}</p><p className="text-xs text-gray-500">{d.user?.email}</p></td><td className="px-4 lg:px-6 py-3 text-emerald-400 font-bold">${d.amount}</td><td className="px-4 lg:px-6 py-3 text-gray-300 uppercase">{d.network||"-"}</td><td className="px-4 lg:px-6 py-3"><code className="text-xs text-gray-400 bg-gray-800 px-2 py-1 rounded">{d.txHash?d.txHash.slice(0,12)+"...":"-"}</code></td><td className="px-4 lg:px-6 py-3 text-gray-500 text-xs">{new Date(d.createdAt).toLocaleDateString()}</td><td className="px-4 lg:px-6 py-3"><B s={d.status}/></td><td className="px-4 lg:px-6 py-3">{d.status==="pending"&&(<div className="flex gap-2"><button onClick={()=>dep(d.id,"approve")} className="p-1.5 text-emerald-400 hover:bg-emerald-500/10 rounded"><Check className="w-4 h-4"/></button><button onClick={()=>dep(d.id,"reject")} className="p-1.5 text-red-400 hover:bg-red-500/10 rounded"><X className="w-4 h-4"/></button></div>)}</td></tr>))}</tbody></table></div>)}

{tab==="withdrawals"&&(<div className="bg-gray-900/60 border border-gray-800 rounded-xl overflow-hidden"><div className="p-4 lg:p-6 border-b border-gray-800"><h2 className="text-xl font-bold text-white flex items-center gap-2"><ArrowUpRight className="w-5 h-5 text-amber-400"/>Withdrawals</h2></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-800">{["User","Amount","Wallet","Date","Status","Actions"].map(h=>(<th key={h} className="px-4 lg:px-6 py-3 text-left text-xs font-medium text-gray-400 uppercase">{h}</th>))}</tr></thead><tbody>{withdrawals.map((w:any)=>(<tr key={w.id} className="border-b border-gray-800/50 hover:bg-gray-800/30"><td className="px-4 lg:px-6 py-3"><p className="text-white font-medium">{w.user?.name}</p><p className="text-xs text-gray-500">{w.user?.email}</p></td><td className="px-4 lg:px-6 py-3 text-amber-400 font-bold">${w.amount}</td><td className="px-4 lg:px-6 py-3"><code className="text-xs text-gray-400 bg-gray-800 px-2 py-1 rounded">{w.walletAddress?w.walletAddress.slice(0,10)+"...":""}</code></td><td className="px-4 lg:px-6 py-3 text-gray-500 text-xs">{new Date(w.createdAt).toLocaleDateString()}</td><td className="px-4 lg:px-6 py-3"><B s={w.status}/></td><td className="px-4 lg:px-6 py-3">{w.status==="pending"&&(<div className="flex gap-2"><button onClick={()=>wit(w.id,"approve")} className="p-1.5 text-emerald-400 hover:bg-emerald-500/10 rounded"><Check className="w-4 h-4"/></button><button onClick={()=>wit(w.id,"reject")} className="p-1.5 text-red-400 hover:bg-red-500/10 rounded"><X className="w-4 h-4"/></button></div>)}</td></tr>))}</tbody></table></div>)}

{tab==="users"&&(<div className="bg-gray-900/60 border border-gray-800 rounded-xl overflow-hidden"><div className="p-4 lg:p-6 border-b border-gray-800"><h2 className="text-xl font-bold text-white">Users ({users.length})</h2></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-800">{["User","Email","Balance","Invested","Refs","Joined","Status","Actions"].map(h=>(<th key={h} className="px-4 lg:px-6 py-3 text-left text-xs font-medium text-gray-400 uppercase">{h}</th>))}</tr></thead><tbody>{users.map((u:any)=>(<tr key={u.id} className="border-b border-gray-800/50 hover:bg-gray-800/30"><td className="px-4 lg:px-6 py-3"><div className="flex items-center gap-3"><div className="w-8 h-8 rounded-full bg-gradient-to-br from-cyan-500 to-emerald-500 flex items-center justify-center"><span className="text-white text-xs font-bold">{u.name?.[0]?.toUpperCase()||"U"}</span></div><div><p className="font-medium text-white">{u.name}</p><p className="text-xs text-gray-500">{u.referralCode}</p></div></td><td className="px-4 lg:px-6 py-3 text-gray-300 text-xs">{u.email}</td><td className="px-4 lg:px-6 py-3 text-gray-300">${Number(u.wallet?.balanceWallet||0).toLocaleString()}</td><td className="px-4 lg:px-6 py-3 text-emerald-400">${Number(u.wallet?.poolWallet||0).toLocaleString()}</td><td className="px-4 lg:px-6 py-3 text-gray-300">{u._count?.referrals||0}</td><td className="px-4 lg:px-6 py-3 text-gray-500 text-xs">{new Date(u.createdAt).toLocaleDateString()}</td><td className="px-4 lg:px-6 py-3"><B s={u.status}/></td><td className="px-4 lg:px-6 py-3">{u.role!=="admin"&&(<button onClick={()=>block(u.id,u.status)} className={\`px-3 py-1 rounded text-xs font-medium transition-colors \${u.status==="blocked"?"bg-emerald-500/20 text-emerald-400 hover:bg-emerald-500/30":"bg-red-500/20 text-red-400 hover:bg-red-500/30"}\`}>{u.status==="blocked"?"Unblock":"Block"}</button>)}</td></tr>))}</tbody></table></div>)}

</div>
);
}`;
fs.writeFileSync('app/admin/page.tsx', code, 'utf8');
console.log('Done - wrote', code.length, 'chars');
